export default {
  domain: "Domain Name",
  lang: "English",
  en: "English",
  zh: "Chinese",
  save: "save",
  default: "default",
  sidebar: {
    gzjczl: "information",
    gwxswh: "PostCoefficientMaintenance",
    gzsd: "WorkTime",
    gxgjwh: "ProcessPriceMaintenance",
    ycqtswh: "AttendanceDaysShallBeMaintained",
    dxwh: "BaseSalaryMaintenance",
    gzjs: "payroll",
    sbsxsd: "SettingOfSocialSecurityCoefficient",
    gztj: "wageStatistics",
    lsgz: "TemporaryPay"
  },
  ProWorkflowInfo: {
    //LD
    pfl: "Amount of formula",
    bf: "Fabric width",
    dxjjs: "Set the machine speed",
    bfhhbj: "cloth is sealed back",
    xd: "Slope",
    yl: "Pressure",
    wd: "Temperature",
    cjkz: "G the machine",
    xh: "Cycle",
    bz: "Note",
    ybll: "Bath ratio theory",
    ybsj: "Bath than the actual",
    ysjs: "Dyeing machine speed",
    xsl: "Bibulous rate",
    jlsl: "Feed water",
    name: "Name",
    cbl: "Exceed bid ~ cannot be in add",
    ysjl: "This version of the existing data can not do this operation!",
    dppfb: "Embryo formulation table",
    zlpfb: "Cooking formula table",
    zxpfb: "Soap formula table",
    rspfb: "Dyeing formula table",
    dxpfb: "Shaping formula table",

    // base
    add: "add",
    delete: "delete",
    submit: "submit",
    colorNO: "colorNO",
    versionNO: "versionNO",
    generate: "generate",
    cancel: "cancel",
    Determine: "Determine",
    cxtj: "query condition",
    gjc: "keyword",
    sbxh: "unit type ",
    gs: "formula",
    gjcmc: "keyword name",
    gjcms: "describe",
    query: "query",
    name: "Name",
    qxzbbh: "Please select the version number first",
    // 生产管理   化验室 ==================
    pqbh: "schedule NO",
    calendar: "calendarID",
    rlbc: "Calendar name",
    xh: "number",
    rlbh: "Calendar code",
    sbsj: "work shift",
    xbsj: "Closing  time",
    gzxl: "efficiency",
    gxmc: "Procedure name",
    scsl: "pro Account",
    scpqmc: "schedule name",
    kssj: "start time",
    xcsj: "end time",
    cjsj: "Creation time",
    cjsr: "Founder",
    colorID: "colorID",
    versionOID: "versionOID",
    versionNUM: "version Number",
    versionName: "versionName",

    Serial: "Serial number",
    // 请输入colorID
    inputColorID: "please input color id",

    inputVersion: "please input version",
    code: "code",
    scLD: "make ID",
    dsc: "generated/notification",
    lddy: "LD Proof",
    versionID: "version ID",
    sbxx: "equipment information",

    flid: "Classification id",
    qyid: "Regional id",
    szmc: "Equipment name",
    sbbh: "Equipment num",
    hzb: "Abscissa",
    zzb: "Ordinate",
    js: "speed",
    zt: "status",
    cl: "constant",
    dw: "Company",
    jlfsL: "Measurement ",
    // page5
    yyid: " relationship ID",
    xxxxid: "Detail ID",
    jcxid: "Check item ID",
    dp: "embryo ",
    sl: "Scouring ",
    zx: "Parameters ",
    rs: "Dyeing",
    dx: "distribution ",
    ds: "Setting parameters",
    sjmc: "setup name",
    hh: "Line number",
    rhllx: "Dyestuff ",
    sldw: "proUnit",
    rhldh: "dyestuff",
    js: "compute",
    pfyl: "Formula ",
    lg: "Material ",
    rcsh: "dyeColorNo",
    fcbl: "ratio",
    al: "Auxiliary",
    sjbh: "setup code",
    dyid: "salLdNoticeoid",
    szms: "setup detaiil",
    bds: "setup Expression",
    dsblx: "runcolorType",
    dybh: "ldCode",
    Distribution: "Distribution",
    sjfl: "setup classification",

    // LD 化验室

    scpf: "Formulation",
    scsbd: "GenerateBoardlist",

    scpqid: "Production schedule ID",
    ysbh: "Bulk acceptance No",
    ddblmx: "Order fabric"
  },
  basesalary: {
    ygbh: "number",
    ygxm: "name",
    jb: "level",
    zj: "Rank",
    gsmc: "company",
    zxmc: "center",
    bmmc: "departmen",
    kmc: "Courses",
    gwmc: "post",
    q: "stage",
    jxlb: "category",
    yf: "month",
    nf: "year",
    dx: "base pay",
    sqdx: "earlier stage",
    bc: "save/add",
    qk: "empty",
    cx: "inquire",
    bz: "remarks",
    mydxwh: "Monthly base salary maintenance"
  },
  procedure: {
    jggxdh: "Process code",
    jggxmc: "Process name",
    jgxm: "Processing projects",
    gzxs: "Wage coefficient",
    bz: "remark",
    gwxswh: "Post coefficient maintenance"
  },
  hours: {
    gzgssd: "Salary formula setting",
    gzsdmc: "Name of working period",
    sbsj: "office hours",
    xs: "hour",
    fz: "minute",
    xbsj: "closing time",
    sc: "delete",
    qk: "clear",
    xh: "serial number",
    gzrlx: "Working day type",
    jxfs: "Paid for way",
    zcsbgzgs1: "Normal working salary formula 1",
    zcsbgzgs2: "Normal working salary formula 2",
    jbgzgs1: "Formula 1 for overtime pay",
    jbgzgs2: "Formula 2 for overtime pay",
    gzsdygzgssd: "Working hours and salary formula set"
  },
  labour: {
    add: "add",
    ksrq: "start date",
    jsrq: "date closed",
    bzdj: "Standard unit price",
    zl: "kind",
    xs: "coefficient",
    sbyxsjcxs: "Device running time from (hour)",
    sbyxsjzxs: "Equipment running time to (hour)",
    sbmc: "devicename",
    fzsyqdj: "Copy the unit price of the last installment",
    sbyxsj: "unit run-time",
    pz: "variety",
    qgxgj: "Period process price",
    gxgjcs: "Process price parameters",
    qymqgxgjwh: "Phase and each process price maintenance",
    qsrpzjxtj: "Please input varieties to add",
    qsrsbmcjxtj: "Please enter the device name to add",
    fzsyqjl: "Copy the record price of the last installment"
  },
  attendance: {
    zlfcq: "No attendance on Saturdays",
    zrfcq: "Non-attendance on Sundays",
    jsfcqrq: "Calculate non-attendance dates",
    xz: "newly increased ",
    sxycqts: "Refresh attendance days",
    ycqts: "Days of attendance required",
    fcqrq: "Non-attendance date",
    mqycqtswh: "Attendance days shall be maintained for each period",
    qcxsj: "Please check the data",
    qxztj: "Please select conditions!",
    qfz: "Please assign a value",
    qxznf: "Please select year",
    qxzy: "Please select year please select month",
    qxzq: "Please select a period",
    s: "up",
    x: "rest",
    t: "sky",
    success: "save success",
    fail: "save fail",
    qcxsj1: "Please check the data"
  },
  social: {
    sbzfxssd: "Social security/miscellaneous coefficient setting",
    grsdsgs: "Individual income tax formula",
    sygw: "Suitable post",
    xzsygw: "Select suitable position",
    xz: "types of insurance ",
    grhgs: "Individuals/companies",
    blhgs: "Ratio/formula",
    czx: "With reference to item",
    jsje: "Base amount",
    bl: "Percentage (%)",
    gs: " formula",
    jjc: "Notches from",
    jjz: "Notch to",
    sl: "Tax rate (%)",
    ljce: "A progressive difference"
  },
  statistics: {
    zzjg: "organization",
    sdxh: "Time serial number",
    gzsd: "Work time",
    gzrqlx: "Work date type",
    sx: "wage ",
    zccqss: "Normal attendance hours",
    zccdhztss: "Normal hours of late arrival/early departure",
    zccqjs: "Normal attendance",
    zccqgzgs1: "Regular attendance salary formula 1",
    zccqgzgs2: "Regular attendance salary formula 2",
    zccqgz1: "Normal attendance salary 1",
    zccqgz2: "Normal attendance salary 2",
    zccqkx: "Regular attendance is deducted",
    jbss: "overtime hours",
    jbcdhztss: "Overtime late/leave early hours",
    jbjs: "The quantity of work overtime",
    jbgz1: "Overtime pay 1",
    jbgz2: "Overtime pay 2",
    jbkx: "Button to work overtime pay",
    jqfl: "Classification of holiday",
    jqmc: "Name of the holiday",
    jqss: "Vacation hours",
    yxhwx: "New/unpaid",
    gzgs: "Salary formula",
    jqgz: "leave pay",
    grhxz: "Individual/group",
    xzbh: "Group number",
    gxbh: "Process id",
    gxmc: "process name ",
    bzgxdj: "Unit price of standard process",
    gwxs: "post coefficient ",
    pzxs: "Variety coefficient",
    sbyxsjxs: "Equipment running time coefficient",
    sbmcxs: "Device name coefficient",
    zccqgzjbgzjqgzzchjbkx:
      "Normal attendance salary + overtime salary + vacation salary - normal/overtime deduction salary",
    rq: "date ",
    qsrjxlb: "Please enter salary category",
    qsrgsmc: "Please enter the company name",
    qsrzxmc: "Please enter the center name",
    qsrbmmc: "Please enter the department name",
    gztj: "wage statistics",
    jsgz: "salary calculator",
    cxgzmx: "Check salary details",
    jbgzgs1: "Formula 1 for overtime pay",
    jbgzgs2: "Formula 2 for overtime pay"
  },
  menuData: {
    hello: "bb",
    // manu
    ProductionName: "Produce",
    Production: [
      //   设备排期
      {
        name: "schedul ",
        data: {
          lineNo: "lineNo",
          chemicalClass: "chemicalClass",
          bcCode: "bcCode",
          calculateClass: "calculateClass",
          formulaValue: "formulaValue",
          seqNo: "seqNo",
          cylinderNo: "cylinderNo",
          fcblValue: "fcblValue",
          zjValue: "zjValue",
          formulaValue: "formulaValue",
          dyeingspeed: "dyeing Speed",
          fabWidth: "fabWidth",
          speed: "speed",
          fabWidth2: "fabWidth2",
          inclination: "inclination",
          press: "press",
          temperature: "temperature",
          fabricWeight: "fabricWeight",
          circulation: "circulation",
          remarks: "remarks",
          waterRatio1: "waterRatio1",
          waterRatio2: "waterRatio2",
          waterAbsorption: "waterAbsorption",
          feedwaterQual: "feedwaterQual",
          waterAbsorption: "waterAbsorption",
          fabricWeight: "fabricWeight",
          circulation: "circulation",
          inclination: "inclination",
          press: "press",
          fabWidth2: "fabWidth2"
        }
      },
      // 生产工序
      {
        name: "process",
        data: ""
      },
      {
        name: "test",
        data: ""
      },
      // 工作日历
      {
        name: "calendar ",
        data: ""
      },
      // 生产排期进度
      {
        name: "progress ",
        data: ""
      },
      // 生产排单
      {
        name: "Production ",
        data: ""
      },
      // 设备类型
      {
        name: " type",
        data: ""
      },
      // 生产拍单逻辑
      {
        name: " logic",
        data: ""
      },
      // 检查方法清单
      {
        name: "check",
        data: ""
      },

      // 计算器
      {
        name: "compute ",
        data: ""
      }
    ],
    LaboratoryName: "Laboratory",
    Laboratory: [
      {
        name: "formula",
        data: ""
      },
      {
        name: "LD Proof",
        data: ""
      },
      {
        name: "cargo",

        data: {
          blmx: "cloth detail",
          //    送板单
          sbd: "cloth",
          dbbh: "Numbering",
          skyq: "color request",
          pc: "batch",
          dbbgs: "swatches ",
          isbb: "isarrange",
          dbbType: "swatchType"
        }
      },

      {
        name: "cloth",
        //    办布布料明细单
        data: {
          blmx: "detail",
          //    送板单
          sbd: "cloth",
          fabId: "fabId",
          colorName: "colorName",
          colorSource: "colorSource",

          custColorNo: "custColorNo",
          dyeColorNo: "dyeColorNo",

          fabQty: "fabQty",
          dataName: "name",
          qtyUnit: "qtyUnit",
          pinNumber: "pinNumber",
          inchNumber: "inchNumber",
          fabBreadth: "fabBreadth",
          breadthUnit: "breadthUnit",
          gramWeight: "gramWeight",
          lateralShrink: "lateralShrink",
          verticalShrink: "verticalShrink",
          twistDegrees: "twistDegrees",
          slopeDegrees: "slopeDegrees",
          fabYcount: "fabYcount",
          dhbh: "labCode"
        }
      }
    ]
  },
  temporary: {
    lsgh: "Temporary workers",
    xm: "name",
    rxhsx: "Daily/hourly pay",
    kqtshsx: "Attendance days/hourly pay",
    yfgz: " wages payable",
    qxzkmc: "Please choose the name of the course",
    qxzrq: "Please select date ",
    lsggz: "Temporary pay",
    lsgzdxz: "Temporary pay - new",
    success: "success!",
    fail: "fail!",
    add: "new Add"
  },
  energy: {
    nonull: "The number or name cannot be empty",
    whdw: "Unit maintenance",
    xgyb: "Modify instrument type",
    qxzygzl: "Please select a category",
    qxzygjcx: "Please select a check first",
    qsr: "Please enter content",
    nyxh: "Energy consumption record / query",
    qk: "empty",
    yblx: "meter",
    wz: "position",
    name: "name",
    blx: "table:",
    z: "to",
    bh: "id",
    dw: "Company",
    cbr: "person",
    dj: "Price",
    cbfs: "mode",
    cbrq: "date",
    cbsj: "time",
    sl: "number",
    qxz: "Please choose",
    dr: "import",
    xz: "Add",
    fwq: "Server lost~",
    qxzlc: "Please select the floor first",
    sccg: "Delete successful！",
    scsb: "Delete failed！",
    scsbs: "Deletion failed, please check for subdata!",
    yqxsc: "Delete cancelled！",
    qrsc: "Are you sure to delete?",
    dr: "Please import excel file",
    tjsb: "Add failure!",
    sfjx:
      "This operation will permanently delete this file. Do you want to continue?",
    ts: "Tips",
    ybzlwh: "Instrument data maintenance",
    scyq: "Delete",
    xztcyb: "add same floor",
    xzzcyb: "add sublayer",
    yqxx: "information:",
    ybdysb: "equipment:",
    lfm: "Cubic metre",
    qke: "Kilogram",
    s: "yes",
    f: "no",
    bc: "Preservation",
    sfyx: "Whether",
    qxzsfyx: "Please select whether it is valid",
    qxzdw: "Please select unit",
    bl: "ratio",
    bz: "Remarks",
    sbdm: "Device code",
    sbmc: "Device name",
    qsrbl: "Please enter multiplying power",
    qsrdj: "Please enter unit price",
    qxzygyb: "Please select a meter",
    sccgong: "Generated successfully!",
    yc: "Server exception, please check parameters",
    cw: "Server error ~ parameter error",
    bccg: "Saved successfully!",
    xzcg: "New success",
    xzsb: "New failure",
    xzsbs: "Failed to add, please check the new content length!",
    gsbycz: "The device already exists",
    fwqyc: "Server exception",
    jybg: "Inspection Report",
    psddh: "Batch color single bulk",
    psdbb: "Batch color single cloth",
    dhsb: "Large delivery panel",
    bbsb: "Cloth delivery board",
    jctj: "Statistics",
    cx: "query",
    ddh: "order",
    kssj: "start",
    jssj: "end",
    jcxm: "Test item",
    tg: "pass",
    wtg: "failed",
    tgl: "pass rate",
    cxcg: "query succeeded",
    fwqcw: "server error",
    scpqgxmx: "Production scheduling process details",
    scpsd: "Generate batch color list",
    sc: "generate",
    psd: "Batch list",
    scpqid: "Production schedule ID",
    gxid: "Process ID",
    rwxh: "Task ordinal number",
    gxmc: "Procedure name",
    czrykz: "Operator snapshot",
    sysb: "Use equipment",
    sxclqd: "Detailed list",
    pqbh: "Schedule number",
    pqid: "Schedule ID",
    xxxxid: "Detail ID",
    wcsj: "Completion time",
    pstgbz: "Color mark",
    wlpj: "Physical evaluation",
    hxpj: "Chemical evaluation",
    wljl: "Physical conclusion",
    hxjl: "Chemical conclusion",
    zdr: "Single person",
    qcjyr: "QC inspector",
    qcjysj: "QC inspection time",
    hyr: "Laboratory personnel",
    hyd: "Laboratory list",
    hysj: "Laboratory time",
    psid: "Batch color ID",
    scsbai: "Generation failure",
    xgcg: "Modified success!",
    xgsb: "Modification failed!",
    xgsbs: "Failed to modify, please check the length of the modified content!",
    ck: "view",
    cz: "operation",
    bj: "Edit",
    schu: "Delete",
    jlmc: "record name",
    ssbh: "ownership No.",
    ssgx: "operation",
    sscl: "owning material",
    bgfl: "report classification",
    qx: "Cancel",
    qd: "OK",
    qdsc: "",
    jlid: "record ID",
    cjsj: "creation time",
    cjr: "creator",
    ssdd: "order",
    jcjg: "check result",
    jcbgfl: "Report classification",
    jcxid: "check item ID",
    jczl: "Varieties",
    jcxxh: "check item no.",
    jcxbh: "check item number",
    jcxmc: "check item name",
    ckbz: "reference standard",
    kjsfw: "acceptable range",
    sH: "description (objective data / subjective evaluation)",
    csjg: "test results",
    pp: "judgment",
    clyj: "processing comments",
    sxsb: "required device",
    xgxmjg: "modify project result",
    zljclx: "quality check type",
    jcx: "check item",
    tjhy: "add laboratory inspection results",
    flmc: "classification name",
    flbh: "classification number",
    flms: "classification Description:",
    xg: "modify",
    qsrflmc: "please enter the classification name",
    qsrflbh: "please enter the classification number",
    qsrflms: "please enter the classification description",
    flid: "classification ID",
    zlbh: "category number",
    xh: "Number",
    qsrxh: "please enter the serial number",
    zlmc: "type name",
    qsrzlmc: "please enter the type name",
    zlms: "type description",
    qsrjcxbh: "please enter the check item number",
    qsrjcxmc: "please enter the check item name",
    qsrckbz: "please enter reference standard",
    qsrkjsfw: "please enter the acceptable range",
    qsrbz: "please enter comments",
    qsrsxsb: "please input the required device",
    gg: "Specifications",
    jsbz: "Acceptable range",
    ckff: "Reference standard ",
    ggjebz: "Specification/acceptance criteria",
    ckffms: "Standard description",
    ggmc: "Specifications name",
    qsrggmc: "Please enter the specification name"
  },
  Shipping: {
    wc: "done",
    hyjhbh: "Freight Plan No.",
    hygsmc: "Corporate name",
    kq: "guest period",
    myfs: "trade mode",
    ysfs: "Type of shipping",
    spzt: "approval status",
    fylb: "expense category",
    fyje: "fee amount",
    jedw: "amount unit",
    bz: "remarks",
    sji: "Actual",
    yszt: "trans body",
    sr: "input",
    scjl: "Delete record",
    qxzjl: "Please select a record!",

    qsrzqdje: "please enter the correct amount",
    hygs: "freight company",
    kqy: "from",
    kqz: "guest period to",
    hyjhscrq: "Planned date",
    hyjhzhxgrq: "Last modified date",
    cyr: "carrier",
    cyrlxdh: "Carrier phone",
    cdf: "undertaker",
    z: "to",
    ysjdb: "Transportation schedule",

    krhth: "guest Contract No.",
    krddh: "guest order number",
    poh: "Po No.",
    kq: "guest period",
    shdz: "receiving address",
    blmc: "cloth class name",
    ys: "color",
    sl: "quantity",
    shr: "consignee",
    shrlxfs: "consignee contact",
    jh: "planned / actual",
    lcrq: "departure date",
    dfhgrq: "date of arrival at shipment port",
    lfhgrq: "departure date",
    dshgrq: "date of arrival at receiving port",
    lshgrq: "date of departure from receiving port",
    shwcrq: "receiving completion date",
    jhua: "planning",
    ysjdbxls: "transportation schedule.xlsx",
    bc: "save",
    gb: "off",
    dc: "export excel",
    qrgb: "are you sure to close? ",
    sj: "actual",
    qqsb: "request failed",
    fyxmlr: "Expense item entry"
  },
  CustomsClearance: {
    dcsb: "fail",
    ycz: "Already exist",
    dc: "export excel",
    jczl: "master data",
    mxzl: "details",
    sccg: "success",
    del: "delete",
    xz: "add",
    djsc: "click Upload",
    scsbai: "upload failed",
    hqwjsj: "get file data",
    hqsb: "failed to get",
    qrsc: "are you sure to delete? ",
    scsb: "delete failed",
    qxbcjbzl: "please save the basic data first",
    qxzjl: "please select a record! ",
    fj: "Enclosure",

    bj: "Edit",
    cx: "query",
    qk: "clear",
    bgqg: "customs declaration / clearance",
    lb: "category",
    hyjhbh: "Freight Plan No.",
    ayfs: "mode of trade",
    ysfs: "mode of transport",
    kqy: "customer period from",
    z: "to",
    hyjhbh: "Freight Plan No.",
    kqz: "guest period to",
    hgmc: "Customs name",
    sbrq: "reporting date",
    jk: "import / export date",
    bjmmjbz: "mark code and remarks",
    // 出境關別
    cjgbdm: "departure clearance code",
    cjgbmc: "departure clearance name",
    ydgdidm: "arrival at port code",
    ydgdimc: "arrival at port name",
    zygdm: "port of destination code",
    zygmc: "port of destination name",
    bc: "save",
    ylrbh: "pre entry No.",
    hgbhdm: "customs number code",
    hgbhmc: "Customs No.-name",
    htxyh: "contract agreement",
    jnshrdm: "domestic consignee code",
    jnshrmc: "domestic consignee name",
    jjgbdm: "entry customs code",
    jjgbmc: "entry customs-name",
    jkrq: "import date",
    ckrq: "export date",
    bah: "record No.",
    jwfhr: "overseas consignor",
    yxgj: "name of means of transport and voyage number",
    tydh: "delivery No.",
    hwcfdd: "place of storage of goods",
    xfsydwdm: "consumer use unit code",
    xwsydwmc: "consumer user name",
    jgfsdm: "supervision method code",
    jgfsmc: "supervision method name",
    zmxzdm: "nature code of levy and exemption",
    zmxzmc: "nature of exemption-name",
    xkzh: "license number",
    qygdm: "port of departure code",
    qygmc: "port of departure - name",
    mygdm: "trading country (region)-Code",
    mygmc: "trading country (region)-name",
    qygdqdm: "country (region)-Code",
    qygdqmc: "country (region)-name",
    jtgdm: "stop port code",
    jtgmc: "stop port name",
    rjkadm: "port of entry code",
    rjkamc: "port of entry - name",
    ljkadm: "departure port code",
    ljkamc: "port of departure-name",
    bzzldm: "package type code",
    bzzlmc: "packing type name",
    js: "number of pieces",
    mzdw: "gross weight unit",
    mz: "gross weight",
    yf: "Freight",
    jzdw: "net weight unit",
    jz: "net weight",
    cjfsdm: "transaction method code",
    cjfsmc: "transaction method name",
    bf: "premium",
    zf: "miscellaneous expenses",
    sfdzjbh: "attached documents and numbers",

    spbh: "commodity number",
    spmcjggxh: "Specification type",
    sljdw: "quantity and unit",
    djzjbz: "unit price / total price / currency system",
    ycgdq: "country of origin (region)",
    zzmdgdq: "final destination country (region)",
    jnmdd: "domestic destination",
    zt: "exemption",
    ywwj: "business foreign key",
    wjm: "filename",
    wj: "file",
    wjlx: "file type",
    jkqg: "Import Clearance"
  },
  caidan: {
    pzgl: "Quality",
    zlxmgl: "Quality Assurance",
    hysjc: "Laboratory",
    psgl: "Batch color",
    jctj: "Testing",
    nygl: "Energy",
    ybwh: "instrument maintenance",
    nhjl: "energy consumption record",
    cwgl: "Shipping",
    ysjdb: "transportation schedule",
    xmfylr: "project cost entry",
    fytjbb: "expense statistics report",
    bgqggl: "Customs clearance management",
    rypb: "Scheduling",
    czryxx: "Operator information",
    gzpbgz: "Work scheduling rules"
  },
  scheduling: {
    cxtj: "query criteria",
    czid: "operation ID",
    rlid: "Calendar ID",
    ryxm: "Name",
    rygw: "Staff post",
    cx: "query",

    kssj: "start time",
    jssj: "End time",
    cfpl: "Repetition rate",
    ksrq: "Start date",
    jsrq: "End date",
    rlmc: "Calendar name"
  },
  proReport: {
    jybg: "Inspection report",
    scjybg: "Generate inspection report",
    jyzl: "Types of inspection",
    zwsj: "Temporarily no data",
    jlmc: "Record the name",
    qsrmc: "Please enter name",
    cjr: "Creator",
    qsrcjr: "Please enter the creator",
    bh: "Number",
    ssph: " Batch number",
    ssdd: "Belong to the order",
    ssgh: "Tank no",
    cjsj: "Creation time",
    sm: "Instructions",
    csjg: "Test results",
    pp: "Judge",
    clyj: "Processing opinion",
    sxsb: "Required equipment",
    bz: "Remarks",
    qsrsm: "Please enter the description",
    qsrjg: "Please enter the result",
    qsrpp: "Please enter judgment",
    qsrclyj: "Please enter processing comments",
    qsrsxsb: "Please enter the required equipment",
    qsrbz: "Please enter remarks",
    jzz: "Loading ···"
  }
};
