export default {
  test: "Chức năng biến tên",
  sidebar: {
    gzjczl: "工資基礎資料",
    gwxswh: "Bảo trì nhân tố",
    gzsd: "Giờ làm việc và thiết lập công thức tiền lương",
    gxgjwh: "Quy trình bảo trì giá",
    ycqtswh: "Nên duy trì ngày bảo trì",
    dxwh: "Bảo trì lương sàn",
    gzjs: "Tính lương",
    sbsxsd: "Thiết lập hệ số an sinh xã hội",
    gztj: "Thống kê tiền lương",
    lsgz: "Tiền lương tạm thời"
  },
  ProWorkflowInfo: {
    cxtj: "Tiêu chí truy vấn",
    gjc: "Từ khóa",
    sbxh: "mô hình thiết bị",
    pqbh: "Số lịch trình sản xuất",
    gs: "công thức",
    gjcmc: "Tên từ khóa",
    gjcms: "Mô tả từ khóa",
    query: "Truy vấn",
    dp: "bảng tham số phôi cố định",
    sl: "Bảng thông số nấu ăn",
    zx: "Bảng thông số xà phòng",
    rs: "Bảng thông số nhuộm",
    dx: "Bảng phân bổ daxing",
    hh: "số dòng",
    rhllx: "Loại thuốc nhuộm",

    rhldh: "Mã thuốc nhuộm",
    js: "Tính toán",
    pfyl: "Liều lượng công thức",
    lg: "Bát",
    fcbl: "Tỷ lệ chấm điểm",
    sldw: "Đơn vị số lượng",
    dybh: "số chứng minh",
    rcsh: "Số nhà máy nhuộm",
    Distribution: "Làm số kiểm tra",
    dsblx: "Kiểu swatch",
    al: "Phụ trợ",
    // trang2
    calendar: "ID lịch",
    rlbc: "Lịch ca",
    xh: "Số sê-ri",
    rlbh: "Số lịch",
    sbsj: "Giờ làm việc",
    xbsj: "Sau giờ",
    gzxl: "Tần suất làm việc",
    gxmc: "Tên quy trình",
    // trang3
    scsl: "Số lượng sản xuất",
    scpqmc: "Tên lịch trình sản xuất",
    kssj: "Thời gian bắt đầu",
    xcsj: "Hoàn thành thực tế",
    cjsj: "Thời gian sáng tạo",
    dyid: "ID thông tin thông báo LD tương ứng",
    cjsr: "Người tạo",
    colorID: "ID màu",
    sbxx: "Thông tin loại thiết bị",

    code: "Mã hóa",
    dsc: "Thông báo L / D sẽ được tạo",
    lddy: "Chứng minh LD",
    versionID: "số phiên bản",
    flid: "ID lớp",
    qyid: "Id khu vực",
    szmc: "đặt tên",
    sbbh: "số thiết bị",
    hzb: "abscissa",
    zzb: "xuất gia",
    js: "tốc độ máy",
    zt: "Trạng thái",
    cl: "Không đổi",
    dw: "Đơn vị",
    jlfsL: "Phương pháp đo sáng",

    scLD: "Tạo thông báo LD",
    // trang5
    yyid: "ID quan hệ tham chiếu",
    xxxxid: "ID chi tiết",
    jcxid: "Kiểm tra ID mục",

    // trang7

    sjmc: "đặt tên",
    sjbh: "đặt số",
    szms: "Cài đặt mô tả",
    bds: "Đặt biểu thức",
    sjfl: "Đặt danh mục"
  },
  basesalary: {
    ygxm: "Tên nhân viên",
    jb: "cấp độ",
    zj: "Vị trí",
    GSMc: "Tên công ty",
    zxmc: "Tên trung tâm",
    bmmc: "Tên bộ phận",
    kmc: "Tên bài học",
    gwmc: "Tên công việc",
    q: "giai đoạn",
    jxlb: "Danh mục trả tiền",
    yf: "Tháng",
    nf: "Năm",
    dx: "Lương cơ bản",
    sqdx: "Mức lương cơ sở cuối cùng",
    bc: "Lưu",
    qk: "Rỗng",
    cx: "Truy vấn",
    bz: "Nhận xét",
    mydxwh: "Bảo trì lương cơ bản hàng tháng"
  },
  menuData: {
    hello: "bb",
    // manu
    ProductionName: "生产管理",
    Production: [
      //   設備排期
      {
        name: "Thiết bị lịch trình",
        data: {
          lineNo: "Số dòng",
          chemicalClass: "Loại thuốc nhuộm",
          bcCode: "Mã vật liệu nhuộm",
          calculateClass: "Tính toán",
          formulaValue: "Liều lượng công thức",
          seqNo: "Số sê-ri",
          cylinderNo: "Chất liệu",
          fcblValue: "Tỷ lệ chấm điểm",
          zjValue: "Phụ trợ",
          formulaValue: "Lượng công thức",

          fabWidth: "Con dấu vải",
          speed: "Sửa tốc độ máy",
          dyeingspeed: "Tốc độ nhuộm",
          fabWidth2: "Đồng hồ đóng cửa trở lại",
          inclination: "Độ dốc",
          press: "Căng thẳng",
          temperature: "Nhiệt độ",
          fabricWeight: "Trọng lượng giao hàng",
          circulation: "Lưu hành",
          remarks: "Nhận xét",
          waterRatio1: "Lý thuyết tỷ lệ tắm",
          waterRatio2: "Tắm thực tế hơn",

          waterAbsorption: "Hấp thụ nước",
          feedwaterQual: "Cho ăn nước",
          fabricWeight: "Trọng lượng giao hàng",
          circulation: "Lưu hành",
          inclination: "Độ dốc",
          press: "Căng thẳng",
          fabWidth2: "Đồng hồ đóng cửa trở lại"
        }
      },
      // 生產工序
      {
        name: "Quy trình sản xuất",
        data: ""
      },
      {
        name: "Kiểm tra",
        data: ""
      },
      // 工作日曆
      {
        name: "Lịch làm việc",
        data: ""
      },
      // 生產排期進度
      {
        name: "生產排期進度",
        data: ""
      },
      // 生產排單
      {
        name: "生產排單",
        data: ""
      },
      // 設備類型
      {
        name: "設備類型",
        data: ""
      },
      // 生產拍單邏輯
      {
        name: "生產拍單邏輯",
        data: ""
      },
      // 檢查方法清單
      {
        name: "檢查方法清單",
        data: ""
      },

      // 計算器
      {
        name: "計算器 ",
        data: ""
      }
    ],
    LaboratoryName: "化驗室",

    Laboratory: [
      {
        name: "色號工序配方",
        data: ""
      },
      {
        name: "LD打樣",
        data: ""
      },
      {
        name: "大貨送板",
        data: {
          blmx: "大貨布料明細單",
          //    送板單
          sbd: "送板單",
          dbbh: "打辦編號",
          skyq: "色卡要求",
          pc: "批次",
          dbbgs: "本次打色板個數",
          isbb: "是否布辦",
          dbbType: "打色板類型"
        }
      },
      {
        name: "辦布送板",
        //    辦布布料明細單
        data: {
          blmx: "辦布布料明細單",
          //    送板單
          sbd: "送板單",
          fabId: "布料編號",
          colorName: "顏色",
          colorSource: "顏色來源",

          custColorNo: "客人色號",
          dyeColorNo: "染廠色號",
          dataName: "名稱",
          fabQty: "數量",

          qtyUnit: "數量單位",
          pinNumber: "針數",
          inchNumber: "吋數",
          fabBreadth: "幅寬/布封",
          breadthUnit: "布封單位",
          gramWeight: "克重",
          lateralShrink: "橫縮",
          verticalShrink: "直縮",
          twistDegrees: "扭度",
          slopeDegrees: "斜度",
          fabYcount: "布料描述",
          dhbh: "大貨檢驗編號"
        }
      },
      {
        name: "項目檢測報告"
        //    辦布布料明細單
      }
    ]
  },

  procedure: {
    jggxdh: "加工工序代號",
    jggxmc: "加工工序名稱",
    jgxm: "加工專案",
    gzxs: "工資係數",
    bz: "備註",
    gwxswh: "崗位係數維護"
  },
  hours: {
    gzgssd: "工資公式設定",
    gzsdmc: "工作時段名稱",
    sbsj: "上班時間",
    xs: "小時",
    fz: "分鐘",
    xbsj: "下班時間",
    sc: "刪除",
    qk: "清空",
    xh: "序號",
    gzrlx: "工作日類型",
    jxfs: "計薪方式",
    zcsbgzgs1: "正常上班工資公式1",
    zcsbgzgs2: "正常上班工資公式2",
    jbgzgs1: "加班工資公式1",
    jbgzgs2: "加班工資公式2",
    gzsdygzgssd: "工作時段與工資公式設定"
  },
  labour: {
    add: "新增",
    ksrq: "開始日期",
    jsrq: "結束日期",
    bzdj: "標準單價",
    zl: "種類",
    xs: "係數",
    sbyxsjcxs: "設備運行時間從(小時)",
    sbyxsjzxs: "設備運行時間至(小時)",
    sbmc: "設備名稱",
    fzsyqdj: "複製上一期單價",
    sbyxsj: "設備運行時間",
    pz: "品種",
    qgxgj: "期工序工價",
    gxgjcs: "工序工價參數",
    qymqgxgjwh: "期與每期工序工價維護",
    qsrpzjxtj: "請輸入品種進行添加",
    qsrsbmcjxtj: "請輸入設備名稱進行添加",
    fzsyqjl: "複製上一期記錄"
  },
  attendance: {
    zlfcq: "週六非出勤",
    zrfcq: "周日非出勤",
    jsfcqrq: "計算非出勤日期",
    xz: "參照選中行新增",
    sxycqts: "刷新應出勤天數",
    ycqts: "應出勤天數",
    fcqrq: "非出勤日期",
    mqycqtswh: "每期應出勤天數維護",
    qcxsj: "請查詢數據",
    qxztj: "請選擇條件！",
    qfz: "請賦值",
    qxznf: "請選擇年份",
    qxzy: "請選擇月",
    qxzq: "請選擇期",
    s: "上",
    x: "休",
    t: "天",
    success: "保存成功！",
    fail: "保存失敗",
    qcxsj1: "請查詢數據，並進行計算"
  },
  social: {
    sbzfxssd: "社保/雜費係數設定",
    grsdsgs: "個人所得稅公式",
    sygw: "適用崗位",
    xzsygw: "選擇適用崗位",
    xz: "險種",
    grhgs: "個人/公司",
    blhgs: "比例/公式",
    czx: "參照項",
    jsje: "基數金額",
    bl: "比例(%)",
    gs: "公式",
    jjc: "級距從",
    jjz: "級距至",
    sl: "稅率(%)",
    ljce: "累進差額"
  },
  statistics: {
    zzjg: "組織架構",
    sdxh: "時段序號",
    gzsd: "工作時段",
    gzrqlx: "工作日期類型",
    sx: "時薪",
    zccqss: "正常出勤時數",
    zccdhztss: "正常遲到/早退時數",
    zccqjs: "正常出勤件數",
    zccqgzgs1: "正常出勤工資公式1",
    zccqgzgs2: "正常出勤工資公式2",
    zccqgz1: "正常出勤工資1",
    zccqgz2: "正常出勤工資2",
    zccqkx: "正常出勤扣薪",
    jbss: "加班時數",
    jbcdhztss: "加班遲到/早退時數",
    jbjs: "加班件數",
    jbgz1: "加班工資1",
    jbgz2: "加班工資2",
    jbkx: "加班扣薪",
    jqfl: "假期分類",
    jqmc: "假期名稱",
    jqss: "假期時數",
    yxhwx: "有新/無薪",
    gzgs: "工資公式",
    jqgz: "假期工資",
    grhxz: "個人/小組",
    xzbh: "小組編號",
    gxbh: "工序編號",
    gxmc: "工序名稱",
    bzgxdj: "標準工序單價",
    gwxs: "崗位係數",
    pzxs: "品種係數",
    sbyxsjxs: "設備運行時間係數",
    sbmcxs: "設備名稱係數",
    zccqgzjbgzjqgzzchjbkx: "正常出勤工資+加班工資+假期工資-正常/加班扣薪",
    rq: "日期",
    qsrjxlb: "請輸入計薪類別",
    qsrgsmc: "請輸入公司名稱",
    qsrzxmc: "請輸入中心名稱",
    qsrbmmc: "請輸入部門名稱",
    gztj: "工資統計",
    jsgz: "計算工資",
    cxgzmx: "查詢工資明細",
    jbgzgs1: "加班工資公式1",
    jbgzgs2: "加班工資公式2"
  },
  temporary: {
    lsgh: "臨時工號",
    xm: "姓名",
    rxhsx: "日薪/時薪",
    kqtshsx: "考勤天數/時薪",
    yfgz: "應付工資",
    lsgh: "臨時工號",
    qxzkmc: "請選擇課名稱",
    qxzrq: "請選擇日期 ",
    lsggz: "臨時工工資",
    lsgzdxz: "臨時工資-新增",
    success: "查詢成功",
    fail: "查詢失敗",
    add: "新增"
  },
  energy: {
    nonull: "編號或名稱不能為空",
    whdw: "單位維護",
    xgyb: "修改仪表类型",
    qsr: "請輸入內容",
    query: "查詢",
    nyxh: "能耗記錄/查詢",
    qk: "清空",
    yblx: "儀錶類型",
    wz: "位置",
    name: "名稱",
    blx: "表類型：",
    z: "至",
    bh: "編號",
    dw: "單位",
    cbr: "抄表人",
    dj: "單價",
    cbfs: "抄表方式",
    cbrq: "抄表日期",
    cbsj: "抄表時間",
    sl: "數量",
    qxz: "請選擇",
    dr: "導入",
    xz: "新增",
    fwq: "伺服器跑丟啦~",
    qjzlc: "請先選擇樓層",
    sccg: "刪除成功！",
    scsb: "刪除失敗！",
    scsbs: "删除失败,请检查是否存在子数据!",
    yqxsc: "已取消刪除！",
    qrsc: "確認刪除？",
    qdr: "請導入excel檔",
    tjsb: "添加失敗",
    sfjx: "此操作將永久刪除該檔, 是否繼續?",
    ts: "提示",
    ybzlwh: "儀錶資料維護",
    scyq: "刪除儀錶",
    xztcyb: "新增同層儀錶",
    xzzcyb: "新增子層儀錶",
    qxzlc: "請先選擇樓層",
    yqxx: "儀器資訊：",
    ybdysb: "儀錶對應設備：",
    lfm: "立方米",
    qke: "千克",
    s: "是",
    f: "否",
    bc: "保存",
    sfyx: "是否有效",
    qxzsfyx: "請選擇是否有效",
    qxzdw: "請選擇單位",
    bl: "倍率",
    bz: "備註",
    sbdm: "設備代碼",
    sbmc: "設備名稱",
    qsrbl: "請輸入倍率",
    qsrdj: "請輸入單價",
    qxzygyb: "請選擇一個儀錶",
    sccgong: "生成成功!",
    yc: "該儀器編號已經存在!",
    cw: "伺服器錯誤~參數錯誤",
    bccg: "保存成功!",
    xzcg: "新增成功",
    xzsb: "新增失敗",
    xzsbs: "新增失败，请检查新增内容长度！",
    gsbycz: "該設備已經存在",
    fwqyc: "單價和倍率只能輸入數字~",
    jybg: "檢驗報告",
    psddh: "批色單大貨",
    psdbb: "批色單辦布",
    dhsb: "大貨送板",
    bbsb: "辦布送板",
    jctj: "檢測統計",
    cx: "查詢",
    ddh: "訂單號",
    kssj: "開始時間",
    jssj: "結束時間",
    jcxm: "檢測專案",
    tg: "通過",
    wtg: "未通過",
    tgl: "通過率",
    cxcg: "查詢成功",
    fwqcw: "伺服器錯誤",
    scpqgxmx: "生產排期工序明細",
    scpsd: "生成批色單",
    sc: "生成",
    psd: "批色單",
    scpqid: "生產排期ID",
    gxid: "工序ID",
    rwxh: "任務序號",
    gxmc: "工序名稱",
    czrykz: "操作人員快照",
    sysb: "使用設備",
    sxclqd: "所需材料清單",
    pqbh: "排期編號(缸號)",
    pqid: "排期ID",
    xxxxid: "詳細資訊ID",
    wcsj: "完成時間",
    pstgbz: "批色通過標誌",
    wlpj: "物理評價",
    hxpj: "化學評價",
    wljl: "物理結論",
    hxjl: "化學結論",
    zdr: "制單人",
    qcjyr: "QC檢驗人",
    qcjysj: "QC檢驗時間",
    hyr: "化驗人",
    hyd: "化驗單",
    hysj: "化驗時間",
    psid: "批色ID",
    scsbai: "生成失敗",
    xgcg: "修改成功",
    xgsb: "修改失敗",
    xgsbs: "修改失败,请检查修改内容长度！",
    ck: "檢查報告",
    cz: "操作",
    bj: "編輯",
    schu: "刪除",
    jlmc: "檢驗報告名稱", //記錄名稱
    ssbh: "編號", //所屬編號
    ssgx: "所屬工序",
    sscl: "所屬材料",
    bgfl: "報告分類",
    qx: "取消",
    qd: "確定",
    jlid: "記錄ID",
    cjsj: "創建時間",
    cjr: "創建人",
    ssdd: "所屬訂單",
    jcjg: "檢查結果",
    jcbgfl: "檢查報告分類",
    jcxid: "檢查項ID",
    jczl: "檢查種類",
    jcxxh: "檢查項序號",
    jcxbh: "檢查項編號",
    jcxmc: "檢查項名稱",
    ckbz: "參考標準",
    kjsfw: "可接受範圍",
    sh: "評估說明",
    csjg: "測試結果",
    pp: "評判",
    clyj: "處理意見",
    sxsb: "所需設備",
    xgxmjg: "修改專案結果",
    zljclx: "品質檢查類型",
    jcx: "檢查項",
    tjhy: "添加化驗室檢查專案結果",
    flmc: "分類名稱",
    flbh: "分類編號",
    flms: "分類描述：",
    xg: "修改",
    qsrflmc: "請輸入分類名稱",
    qsrflbh: "請輸入分類編號",
    qsrflms: "請輸入分類描述",
    flid: "分類ID",
    zlbh: "種類編號",
    xh: "序號",
    qsrxh: "請輸入序號",
    zlmc: "種類名稱",
    qsrzlmc: "請輸入種類名稱",
    zlms: "種類描述",
    qsrjcxbh: "請輸入檢查項編號",
    qsrjcxmc: "請輸入檢查項名稱",
    qsrckbz: "請輸入參考標準",
    qsrkjsfw: "請輸入可接受範圍",
    qsrbz: "請輸入備註",
    qsrsxsb: "請輸入所需設備",
    ckff: "參考方法標準",
    gg: "Specifications",
    jsbz: "Acceptance criteria",
    ggjebz: "規格/接受標準",
    ckffms: "Standard description",
    ggmc: "規格名稱",
    qsrggmc: "Please enter the specification name",
    qxzygzl: "請選擇一個種類",
    qxzygjcx: "請先選擇一個檢查項"
  },
  Shipping: {
    wc: "完成",
    hyjhbh: "貨運計畫編號",
    hygsmc: "貨運公司名稱",
    kq: "客期",
    myfs: "貿易方式",
    ysfs: "運輸方式",
    spzt: "審批狀態",
    fylb: "費用類別",
    fyje: "費用金額",
    jedw: "金額單位",
    yszt: "運輸主體",
    bz: "備註",
    sr: "輸入",
    scjl: "刪除記錄",
    qxzjl: "請選擇記錄！",
    z: "至",
    // ysfy: "運輸費用（工廠 -> 碼頭）",
    // zxgmtf: "裝箱港碼頭費",
    // xhgmtf: "卸貨港碼頭費",
    // ysfygc: "運輸費用（碼頭 -> 工廠）",
    // ysfymt: "運輸費用（碼頭 -> 碼頭）",
    // jkqgf: "進口清關費",
    // ckqgf: "出口清關費",
    // cdzf: "產地證費",
    // bxf: "保險費",
    // gs: "關稅",
    // zzs: "增值稅",
    sji: "實際",
    qsrzqdje: "請輸入正確的金額",
    hygs: "貨運公司",
    kqy: "客期由",
    kqz: "客期至",
    hyjhscrq: "貨運計畫生成日期",
    hyjhzhxgrq: "貨運計畫最後修改日期",
    cyr: "承運人",
    cyrlxdh: "承運人聯繫電話",
    cdf: "承擔方",
    ysjdb: "運輸進度表",

    krhth: "客人契約號",
    krddh: "客人訂單號",
    poh: "PO號",
    kq: "客期",
    shdz: "收貨地址",
    blmc: "布類名稱",
    ys: "顏色",
    sl: "數量",
    shr: "收貨人",
    shrlxfs: "收貨人聯繫方式",
    jh: "計畫/實際",
    lcrq: "離廠日期",
    dfhgrq: "到發貨港日期",
    lfhgrq: "離發貨港日期",
    dshgrq: "到收貨港日期",
    lshgrq: "離收貨港日期",
    shwcrq: "收貨完成日期",
    jhua: "計畫",
    ysjdbxls: "運輸進度表.xlsx",
    bc: "保存",
    gb: "關閉",
    dc: "導出Excel",
    qrgb: "確認關閉？",
    sj: "實際",
    qqsb: "請求失敗",
    fyxmlr: "費用專案錄入"
  },
  CustomsClearance: {
    dcsb: "導出失敗",
    ycz: "已存在",
    dc: "導出Excel",
    jczl: "基礎資料",
    mxzl: "明細資料",
    sccg: "刪除成功",
    xz: "新增",
    del: "刪除",
    djsc: "點擊上傳",
    scsbai: "上傳失敗",
    hqwjsj: "獲取檔數據",
    hqsb: "獲取失敗",
    qrsc: "確認刪除？",
    scsb: "刪除失敗",
    qxbcjbzl: "請先保存基礎資料",
    qxzjl: "請選擇記錄！",
    fj: "附件",
    bj: "編輯",
    cx: "查詢",
    qk: "清空",
    bgqg: "報關/清關",
    lb: "類別",
    hyjhbh: "貨運計畫編號",
    ayfs: "貿易方式",
    ysfs: "運輸方式",
    kqy: "客期由",
    z: "至",
    hyjhbh: "貨運計畫編號",
    kqz: "客期至",
    hgmc: "海關名稱",
    sbrq: "申報日期",
    jk: "進口/出口日期",
    bjmmjbz: "標記嘜碼及備註",

    bc: "保存",
    ylrbh: "預錄入編號",
    hgbhdm: "海關編號-代碼",
    hgbhmc: "海關編號-名稱",
    htxyh: "合同協議號",
    jnshrdm: "境內收貨人-代碼",
    jnshrmc: "境內收貨人-名稱",
    jjgbdm: "進境關別-代碼",
    jjgbmc: "進境關別-名稱",
    cjgbdm: "出境關別-代碼",
    cjgbmc: "出境關別-名稱",
    jkrq: "進口日期",
    ckrq: "出口日期",
    bah: "備案號",
    jwfhr: "境外發貨人",
    yxgj: "運輸工具名稱及航次號",
    tydh: "提運單號",
    hwcfdd: "貨物存放地點",
    xfsydwdm: "消費使用單位-代碼",
    xwsydwmc: "消費使用單位-名稱",
    jgfsdm: "監管方式-代碼",
    jgfsmc: "監管方式-名稱",
    zmxzdm: "征免性質-代碼",
    zmxzmc: "征免性質-名稱",
    xkzh: "許可證號",
    qygdm: "啟運港-代碼",
    qygmc: "啟運港-名稱",
    mygdm: "貿易國(地區)-代碼",
    mygmc: "貿易國(地區)-名稱",
    qygdqdm: "啟運國(地區)-代碼",
    qygdqmc: "啟運國(地區)-名稱",
    jtgdm: "經停港-代碼",
    jtgmc: "經停港-名稱",
    ydgdidm: "運抵港-代碼",
    ydgdimc: "運抵港-名稱",
    zygdm: "指运港-代码",
    zygmc: "指运港-名稱",
    rjkadm: "入境口岸-代碼",
    rjkamc: "入境口岸-名稱",
    ljkadm: "離境口岸-代碼",
    ljkamc: "離境口岸-名稱",
    bzzldm: "包裝種類-代碼",
    bzzlmc: "包裝種類-名稱",
    js: "件數",
    mzdw: "毛重-單位",
    mz: "毛重",
    yf: "運費",
    jzdw: "淨重-單位",
    jz: "淨重",
    cjfsdm: "成交方式-代碼",
    cjfsmc: "成交方式-名稱",
    bf: "保費",
    zf: "雜費",
    sfdzjbh: "隨附單證及編號",

    spbh: "商品編號",
    spmcjggxh: "商品名稱及規格型號",
    sljdw: "數量及單位",
    djzjbz: "單價/總價/幣制",
    ycgdq: "原產國（地區）",
    zzmdgdq: "最終目的國（地區）",
    jnmdd: "境內目的地",
    zt: "征免",
    ywwj: "業務外鍵",
    wjm: "檔案名",
    wj: "檔",
    wjlx: "檔類型",
    jkqg: "報關/清關"
  },
  caidan: {
    pzgl: "品質管理",
    zlxmgl: "品質專案管理",
    hysjc: "化驗室檢查",
    psgl: "批色管理",
    jctj: "檢測統計",
    nygl: "能源管理",
    ybwh: "儀錶維護",
    nhjl: "能耗記錄",
    cwgl: "船務管理",
    ysjdb: "運輸進度表",
    xmfylr: "專案費用錄入",
    fytjbb: "費用統計報表",
    bgqggl: "報關/清關管理",
    rypb: "人員排班",
    czryxx: "操作人員資訊",
    gzpbgz: "工作排班規則"
  },
  scheduling: {
    cxtj: "查詢條件",
    czid: "操作ID",
    rlid: "日曆ID",
    ryxm: "人員姓名",
    rygw: "人員崗位",
    cx: "查詢",

    kssj: "開始時間",
    jssj: "結束時間",
    cfpl: "重複頻率",
    ksrq: "開始日期",
    jsrq: "結束日期",
    rlmc: "日曆名稱"
  },
  common: {
    condition: "条件",
    display: "显示",
    hide: "隐藏"
  },
  tip: {
    select: "请选择",
    input: "请输入"
  },
  date: {
    start: "开始日期",
    end: "结束日期",
    tip: "至",
    t: "今日",
    y: "昨日",
    n: "近7天",
    a: "全部"
  },
  crud: {
    filter: {
      addBtn: "新增条件",
      clearBtn: "清空数据",
      resetBtn: "清空条件",
      cancelBtn: "取 消",
      submitBtn: "确 定"
    },
    tipStartTitle: "当前表格已选择",
    tipEndTitle: "项",
    editTitle: "编 辑",
    addTitle: "新 增",
    viewTitle: "查 看",
    filterTitle: "过滤条件",
    menu: "操作",
    addBtn: "新 增",
    showBtn: "显 隐",
    filterBtn: "过 滤",
    refreshBtn: "刷 新",
    printBtn: "打 印",
    excelBtn: "导 出",
    updateBtn: "修 改",
    cancelBtn: "取 消",
    columnBtn: "多 选",
    searchBtn: "搜 索",
    emptyBtn: "清 空",
    menuBtn: "功 能",
    saveBtn: "保 存",
    viewBtn: "查 看",
    editBtn: "编 辑",
    delBtn: "删 除"
  }
};
